name: Nightly Build
on:
  schedule:
    - cron: '10 05 * * *'
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: AutoModality/action-clean@v1
      - uses: actions/checkout@v2
      - name: Package
        id: package
        uses: AutoModality/action-package-debian-ros@v3
        with:
          dev-repo-entitlement: ${{ secrets.CLOUDSMITH_READ_DEV_ENTITLEMENT }}
          release-repo-entitlement: ${{ secrets.CLOUDSMITH_READ_RELEASE_ENTITLEMENT }}

