name: Story Development

on:
  push:
    branches-ignore:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Package
        uses: AutoModality/action-package-debian-ros@v1.3.1


